name: 'Build Ionic React Router'
description: 'Build Ionic React Router'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - name: ğŸ•¸ï¸ Install Dependencies
      run: npm ci
      shell: bash
      working-directory: ./packages/react-router
    - name: ğŸ”„ Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/react-router
    - name: ğŸ–Œï¸ Lint
      run: npm run lint
      shell: bash
      working-directory: ./packages/react-router
    - name: ğŸ—ï¸ Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react-router
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-react-router
        output: packages/react-router/ReactRouterBuild.zip
        paths: packages/react-router/dist
