name: 'Build Ionic React Router'
description: 'Build Ionic React Router'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - name: Install Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/react-router
    - name: Lint
      run: pnpm run lint
      shell: bash
      working-directory: ./packages/react-router
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./packages/react-router
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-react-router
        output: packages/react-router/ReactRouterBuild.zip
        paths: packages/react-router/dist
