name: 'Release'
description: 'Releases a package'
inputs:
  scope:
    description: 'The package to release. Must match a package specified in lerna.json.'
  version:
    description: 'The type of version to release.'
  tag:
    description: 'The tag to publish to on NPM.'
  preid:
    description: 'The prerelease identifier used when doing a prerelease.'
  working-directory:
    description: 'The directory of the package.'
  folder:
    default: './'
    description: 'A folder containing a package.json file.'
  node-version:
    description: 'Node.js version to use when publishing.'
    required: false
    default: '20'
  registry-url:
    description: 'Registry URL used for npm publish.'
    required: false
    default: 'https://registry.npmjs.org'
runs:
  using: 'composite'
  steps:
    - name: ğŸŸ¢ Configure Node for Publish
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
    # Provenance requires npm 9.5.0+
    - name: ğŸ“¦ Install latest npm
      run: npm install -g npm@latest
      shell: bash
    # This ensures the local version of Lerna is installed
    # and that we do not use the global Lerna version
    - name: ğŸ•¸ï¸ Install root dependencies
      run: npm ci
      shell: bash
    - name: ğŸ“¦ Install Dependencies
      run: npx lerna@5 bootstrap --include-dependencies --scope ${{ inputs.scope }} --ignore-scripts -- --legacy-peer-deps
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: ğŸ·ï¸ Set Version
      run: |
        if [ "${{ inputs.preid }}" = "none" ] || [ -z "${{ inputs.preid }}" ]; then
          npx lerna@5 version ${{ inputs.version }} --yes --exact --no-changelog --no-push --no-git-tag-version
        else
          npx lerna@5 version ${{ inputs.version }} --yes --exact --no-changelog --no-push --no-git-tag-version --preid=${{ inputs.preid }}
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: ğŸ—ï¸ Run Build
      run: npm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: ğŸš€ Publish to NPM
      run: npm publish ${{ inputs.folder }} --tag ${{ inputs.tag }} --provenance
      shell: bash
      working-directory: ${{ inputs.working-directory }}
