name: 'Test Core Screenshot'
description: 'Test Core Screenshot'
inputs:
  shard:
    description: 'Playwright Test Shard (ex: 2)'
  totalShards:
    description: 'Playwright total number of test shards (ex: 4)'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Core Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}-v2
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core-src
        path: ./core
        filename: CoreSrc.zip
    - name: Install Playwright Dependencies
      run: npx playwright install
      shell: bash
      working-directory: ./core
    - name: Test
      run: npx playwright test --shard=${{ inputs.shard }}/${{ inputs.totalShards }}
      shell: bash
      working-directory: ./core
    - name: Archive Test Results
      # The always() ensures that this step
      # runs even if the previous step fails.
      # We want the test results to be archived
      # even if the test fails in the previous
      # step, otherwise there would be no way
      # to debug these tests.
      if: always()
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: test-results-${{ inputs.shard }}-${{ inputs.totalShards }}
        output: core/TestResults-${{ inputs.shard }}-${{ inputs.totalShards }}.zip
        paths: core/test-results core/playwright-report
