name: 'Test Angular E2E'
description: 'Test Angular E2E'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-angular
        path: ./angular
        filename: AngularBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-angular-server
        path: ./packages/angular-server
        filename: AngularServerBuild.zip
    - name: ğŸ§ª Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./packages/angular/test
    - name: ğŸ•¸ï¸ Install Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/angular/test/build/${{ inputs.app }}
    - name: ğŸ“¦ Install Playwright Browsers
      run: npx playwright install
      shell: bash
      working-directory: ./packages/angular/test/build/${{ inputs.app }}
    - name: ğŸ”„ Sync Built Changes
      run: npm run sync
      shell: bash
      working-directory: ./packages/angular/test/build/${{ inputs.app }}
    - name: ğŸ§ª Run Tests
      run: npm run test
      shell: bash
      working-directory: ./packages/angular/test/build/${{ inputs.app }}
