name: 'Test React E2E'
description: 'Test React E2E'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Cache Core Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}-v2
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react-router
        path: ./packages/react-router
        filename: ReactRouterBuild.zip
    - name: Install Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/react/test-app
    - name: Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/react/test-app
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react/test-app
    - name: Run E2E Tests
      run: npm run e2e
      shell: bash
      working-directory: ./packages/react/test-app
