name: 'Test React E2E'
description: 'Test React E2E'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react-router
        path: ./packages/react-router
        filename: ReactRouterBuild.zip
    - name: Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./packages/react/test
    - name: Install Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/react/test/build/${{ inputs.app }}
    - name: Sync Built Changes
      run: npm run sync
      shell: bash
      working-directory: ./packages/react/test/build/${{ inputs.app }}
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react/test/build/${{ inputs.app }}
    - name: Run Tests
      run: npm run e2e
      shell: bash
      working-directory: ./packages/react/test/build/${{ inputs.app }}

