name: 'Test React Router E2E'
description: 'Test React Router'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react-router
        path: ./packages/react-router
        filename: ReactRouterBuild.zip
    - name: ğŸ§ª Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./packages/react-router/test
    - name: ğŸ•¸ï¸ Install Dependencies
      run: npm install
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: ğŸ”„ Sync Built Changes
      run: npm run sync
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: ğŸ—ï¸ Build
      run: npm run build
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
    - name: ğŸ§ª Run Tests
      run: npm run e2e
      shell: bash
      working-directory: ./packages/react-router/test/build/${{ inputs.app }}
