version: 2.1

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}-3

  - &save-cache
      key: dependency-cache-{{ checksum "package.json" }}-3
      paths:
        - node_modules

  - &restore-cache-core
      keys:
        - dependency-cache-{{ checksum "core/package.json" }}-3

  - &save-cache-core
      key: dependency-cache-{{ checksum "core/package.json" }}-3
      paths:
        - core/node_modules

  - &restore-cache-core-stencil
      keys:
        - stencil-cache-2

  - &save-cache-core-stencil
      key: stencil-cache-2
      paths:
        - core/.stencil
        - core/screenshot/images

defaults: &defaults
  docker:
    - image: circleci/node:latest-browsers
  working_directory: /tmp/workspace
  environment:
    NODE_ENV: development

jobs:
  puppeteer-dependencies:
    <<: *defaults
    steps:
    - run:
        name: Install headless Chrome dependencies
        command: |
          sudo apt-get install -yq \
          gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
          fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
    - run:
        name: Install Puppeteer with Chromium
        command: |
          npm i puppeteer

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install --legacy-peer-deps
      - save_cache: *save-cache
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-core:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-core
      - restore_cache: *restore-cache-core-stencil
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/core
      - save_cache: *save-cache-core
      - run:
          command: npm run build -- --ci
          working_directory: /tmp/workspace/core
      - save_cache: *save-cache-core-stencil
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-angular:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/angular
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/angular
      - run:
          command: npm run build
          working_directory: /tmp/workspace/angular
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-angular-server:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/packages/angular-server
      - run:
          command: npm run build.prod
          working_directory: /tmp/workspace/packages/angular-server
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-react:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/packages/react
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/react
      - run:
          command: npm run build
          working_directory: /tmp/workspace/packages/react
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  build-react-router:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/packages/react-router
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/react-router
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/packages/react
      - run:
          command: sudo npm link @ionic/react
          working_directory: /tmp/workspace/packages/react-router
      - run:
          command: npm run build
          working_directory: /tmp/workspace/packages/react-router
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-vue:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/vue
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/vue
      - run:
          command: npm run build
          working_directory: /tmp/workspace/packages/vue
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-vue-router:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install
          working_directory: /tmp/workspace/packages/vue-router
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/packages/vue
      - run:
          command: sudo npm link @ionic/vue
          working_directory: /tmp/workspace/packages/vue-router
      - run:
          command: npm run build
          working_directory: /tmp/workspace/packages/vue-router
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  test-core-clean-build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checking clean build
          command: git diff --exit-code
          working_directory: /tmp/workspace/core

  test-core-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/core

  test-core-e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.e2e --ci
          working_directory: /tmp/workspace/core

  test-core-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.spec --ci
          working_directory: /tmp/workspace/core

  test-core-treeshake:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.treeshake --ci
          working_directory: /tmp/workspace/core

  test-core-screenshot:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Screenshot
          command: npx stencil test --e2e --screenshot --screenshot-connector=scripts/screenshot/ci.js --ci || true
          working_directory: /tmp/workspace/core

  test-core-screenshot-master:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Screenshot
          command: npx stencil test --e2e --screenshot --screenshot-connector=scripts/screenshot/ci.js --ci --update-screenshot || true
          working_directory: /tmp/workspace/core

  test-angular-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/angular

  test-react-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/packages/react

  test-react-router-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/packages/react-router

  test-vue-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/packages/vue

  test-vue-router-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/packages/vue-router

  test-react-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/react
      - run:
          command: npm run test.spec
          working_directory: /tmp/workspace/packages/react

  test-react-router-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/react
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/packages/react
      - run:
          command: sudo npm link @ionic/react
          working_directory: /tmp/workspace/packages/react-router
      - run:
          command: npm run test.spec
          working_directory: /tmp/workspace/packages/react-router

  test-vue-router-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/core
      - run:
          command: sudo npm link @ionic/core
          working_directory: /tmp/workspace/packages/vue
      - run:
          command: sudo npm link
          working_directory: /tmp/workspace/packages/vue
      - run:
          command: sudo npm link @ionic/vue
          working_directory: /tmp/workspace/packages/vue-router
      - run:
          command: npm run test.spec
          working_directory: /tmp/workspace/packages/vue-router

  test-angular-e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm install --legacy-peer-deps
          working_directory: /tmp/workspace/angular/test/test-app
      - run:
          command: npm run test -- --protractor-config=e2e/protractor-ci.conf.js
          working_directory: /tmp/workspace/angular/test/test-app

workflows:
  version: 2
  build:
    jobs:
      - puppeteer-dependencies
      - build
      - build-core:
          requires: [build]
      - test-core-clean-build:
          requires: [build-core]
      - test-core-lint:
          requires: [build-core]
      - test-core-e2e:
          requires: [puppeteer-dependencies, build-core]
      - test-core-spec:
          requires: [build-core]
      # Adam requested we skip this test for now
      # since it is failing on ES5 code which
      # will be removed in Ionic Framework v6
      #- test-core-treeshake:
      #    requires: [build-core]
      - test-core-screenshot:
          requires: [build-core]
          filters:
            branches:
              ignore: master
      - test-core-screenshot-master:
          requires: [build-core]
          filters:
            branches:
              only: master

      - build-angular:
          requires: [build-core]
      - build-angular-server:
          requires: [build-angular]
      - build-react:
          requires: [build-core]
      - build-react-router:
          requires: [build-core, build-react]
      - test-react-lint:
          requires: [build-react]
      - test-react-router-lint:
          requires: [build-react-router]
      - test-react-spec:
          requires: [build-react]
      - test-react-router-spec:
          requires: [build-react-router]
      - build-vue:
          requires: [build-core]
      - build-vue-router:
          requires: [build-core, build-vue]
      - test-vue-lint:
          requires: [build-vue]
      - test-vue-router-lint:
          requires: [build-vue-router]
      - test-vue-router-spec:
          requires: [build-vue-router]
      - test-angular-lint:
          requires: [build-angular]
      - test-angular-e2e:
          requires:
            - build-angular
            - build-angular-server
