name: 'Build Ionic Angular'
description: 'Build Ionic Angular'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.tar
    - name: Install Angular Dependencies
      run: npm ci
      shell: bash
      working-directory: ./angular
    - name: Sync
      run: npm run sync
      shell: bash
      working-directory: ./angular
    - name: Lint
      run: npm run lint
      shell: bash
      working-directory: ./angular
    - name: Build
      run: npm run build
      shell: bash
      working-directory: ./angular
    - name: Check Diff
      run: git diff --exit-code
      shell: bash
      working-directory: ./angular
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-angular
        output: ./angular/AngularBuild.tar
        paths: ./angular/dist
