name: 'Build Ionic Angular'
description: 'Build Ionic Angular'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: ğŸ•¸ï¸ Install Angular Dependencies
      run: npm ci
      shell: bash
      working-directory: ./packages/angular
    - name: ğŸ”„ Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/angular
    - name: ğŸ–Œï¸ Lint
      run: npm run lint
      shell: bash
      working-directory: ./packages/angular
    - name: ğŸ—ï¸ Build
      run: npm run build
      shell: bash
      working-directory: ./packages/angular
    - name: Clean core package.json
      run: git checkout ./package.json
      shell: bash
      working-directory: ./core
    - name: ğŸ” Check Diff
      run: git diff --exit-code
      shell: bash
      working-directory: ./packages/angular
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-angular
        output: ./packages/angular/AngularBuild.zip
        paths: ./packages/angular/dist
