name: 'Test Core Spec'
description: 'Test Core Spec'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: 24.x
    - name: ğŸ•¸ï¸ Install Dependencies
      run: npm ci
      working-directory: ./core
      shell: bash
    - name: ğŸ“¦ Install Stencil ${{ inputs.stencil-version }}
      run: npm install @stencil/core@${{ inputs.stencil-version }}
      shell: bash
      working-directory: ./core
      if: ${{ inputs.stencil-version != '' }}
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: ğŸ§ª Test
      run: npm run test.spec -- --ci
      shell: bash
      working-directory: ./core
