name: 'Test Core Spec'
description: 'Test Core Spec'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: npm ci
      working-directory: ./core
      shell: bash
    - name: Install Stencil ${{ inputs.stencil-version }}
      run: npm install @stencil/core@${{ inputs.stencil-version }}
      shell: bash
      working-directory: ./core
      if: ${{ inputs.stencil-version != '' }}
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: Test
      run: npm run test.spec -- --ci
      shell: bash
      working-directory: ./core
