name: 'Build Ionic Core'
description: 'Build Ionic Core'
inputs:
  ionicons-version:
    description: 'The NPM tag of ionicons to install.'
    type: string
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.x
    - name: üï∏Ô∏è Install Dependencies
      run: npm install
      working-directory: ./core
      shell: bash
    # If an Ionicons version was specified install that.
    # Otherwise just use the version defined in the package.json.
    - name: üì¶ Install Ionicons Version
      if: inputs.ionicons-version != ''
      run: npm install ionicons@${{ inputs.ionicons-version }}
      working-directory: ./core
      shell: bash
    - name: üèóÔ∏è Build Core
      run: npm run build -- --ci
      working-directory: ./core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: core/CoreBuild.zip
        # Include generated proxy files from Stencil output targets so
        # framework builds can detect when they need to be updated
        paths: core/dist core/components core/src/foundations core/css core/hydrate core/loader core/src/components.d.ts core/api.txt packages/angular/src/directives/proxies.ts packages/angular/src/directives/proxies-list.ts packages/angular/standalone/src/directives/proxies.ts packages/vue/src/proxies.ts packages/react/src/components/proxies.ts packages/react/src/components/inner-proxies.ts packages/react/src/components/routing-proxies.ts
