name: 'Build Ionic Core with Stencil Prerelease'
description: 'Build Ionic Core with a Prerelease Build of Stencil'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24.x

    - name: ğŸ•¸ï¸ Install Dependencies
      run: npm ci
      working-directory: ./core
      shell: bash
    - name: ğŸ“¦ Install Stencil ${{ inputs.stencil-version }}
      working-directory: ./core
      run: npm i @stencil/core@${{ inputs.stencil-version }}
      shell: bash
    - name: ğŸ—ï¸ Build Core
      run: npm run build -- --ci --debug --verbose
      working-directory: ./core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: core/CoreBuild.zip
        paths: core/dist core/components core/css core/hydrate core/loader core/src/components.d.ts core/package.json
