name: 'Build Ionic Core with Stencil Prerelease'
description: 'Build Ionic Core with a Prerelease Build of Stencil'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm ci
      working-directory: ./core
      shell: bash
    - name: Install Stencil ${{ inputs.stencil-version }}
      working-directory: ./core
      run: npm i @stencil/core@${{ inputs.stencil-version }}
      shell: bash
    - name: Build Core
      run: npm run build -- --ci
      working-directory: ./core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: core/CoreBuild.zip
        paths: core/dist core/components core/css core/hydrate core/loader core/src/components.d.ts
