name: 'Build Ionic Angular Server'
description: 'Build Ionic Angular Server'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: ğŸ•¸ï¸ Install Angular Server Dependencies
      run: npm ci
      shell: bash
      working-directory: ./packages/angular-server
    - name: ğŸ”„ Sync
      run: npm run sync
      shell: bash
      working-directory: ./packages/angular-server
    - name: ğŸ—ï¸ Build
      run: npm run build.prod
      shell: bash
      working-directory: ./packages/angular-server
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-angular-server
        output: packages/angular-server/AngularServerBuild.zip
        paths: packages/angular-server/dist
