name: 'Build Ionic Angular Server'
description: 'Build Ionic Angular Server'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: Install Angular Server Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/angular-server
    - name: Build
      run: pnpm run build.prod
      shell: bash
      working-directory: ./packages/angular-server
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-angular-server
        output: packages/angular-server/AngularServerBuild.zip
        paths: packages/angular-server/dist
