name: 'Ionic Framework Archive Upload'
description: 'Compresses and uploads an archive to be reused across jobs'
inputs:
  paths:
    description: 'Paths to files or directories to archive'
  output:
    description: 'Output file name'
  name:
    description: 'Archive name'
runs:
  using: 'composite'
  steps:
    - name: Install Dependency
      run: sudo apt-get install zip
      shell: bash
    - name: Create Archive
      run: zip -q -r ${{ inputs.output }} ${{ inputs.paths }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.output }}
