name: 'Ionic Framework Build'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/build-core

  test-core-clean-build:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-clean-build

  test-core-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-lint

  test-core-spec:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-spec

  test-core-e2e:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-e2e

  test-core-screenshot:
    needs: [build-core]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-screenshot
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test-core-screenshot-main:
    needs: [build-core]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-screenshot-main
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-vue:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-vue

  build-vue-router:
    needs: [build-vue]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-vue-router

  test-vue-spec:
    needs: [build-vue, build-vue-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-vue-spec

  test-vue-e2e:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        totalShards: [5]
    needs: [build-vue, build-vue-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-vue-e2e
      with:
        shard: ${{ matrix.shard }}
        totalShards: ${{ matrix.totalShards }}

  build-angular:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-angular

  build-angular-server:
    needs: [build-angular]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-angular-server

  test-angular-e2e:
    needs: [build-angular, build-angular-server]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-angular-e2e

  build-react:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-react

  build-react-router:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-react-router

  test-react-router-e2e:
    needs: [build-react, build-react-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-react-router-e2e

  test-react-e2e:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        totalShards: [5]
    needs: [build-react, build-react-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-react-e2e
      with:
        shard: ${{ matrix.shard }}
        totalShards: ${{ matrix.totalShards }}
