name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: npm ci
    - name: Build Core
      run: npm run build -- --ci
    - name: Create Build Archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -tzip core/CoreBuild.zip core/dist core/components core/css core/hydrate core/loader
    - name: Upload Build Output
      uses: actions/upload-artifact@v2
      with:
        name: ionic-core
        path: core/VueBuild.zip

  build-vue:
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: core-node-modules
      with:
        path: ./core/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Download Core Build Output
      uses: actions/download-artifact@v2
      with:
        name: ionic-core
        path: core/CoreBuild.zip
    - name: Unarchive Core Build Output
      uses: edgarrc/action-7z@v1
      with:
        args: 7z x core/CoreBuild.zip -aoa
    - name: Install Vue Dependencies
      working-directory: ./packages/vue
      run: npm install
    - name: Link @ionic/core
      working-directory: ./core
      run: npm link
    - name: Link @ionic/core in @ionic/vue
      working-directory: ./packages/vue
      run: npm link @ionic/core
    - name: Build
      working-directory: ./packages/vue
      run: npm run build
    - name: Create Build Archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -tzip packages/vue/VueBuild.zip packages/vue/dist packages/vue/css
    - name: Upload Build Output
      uses: actions/upload-artifact@v2
      with:
        name: ionic-vue
        path: packages/vue/VueBuild.zip
