name: 'Update Reference Screenshots'

on:
  workflow_dispatch:

jobs:
  build-core:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Checkout runs this on a --global level, but the global
      # .gitconfig does not exist, so the command is a no-op.
      # See: https://github.com/actions/checkout/issues/1169
      # This leads to the following error:
      # fatal: detected dubious ownership in repository at '/__w/ionic-framework/ionic-framework'
      - run: git config --system --add safe.directory /__w/ionic-framework/ionic-framework
      - uses: ./.github/workflows/actions/build-core

  test-core-screenshot:
    strategy:
      # This ensures that all screenshot shard
      # failures are reported so the dev can
      # review everything at once.
      fail-fast: false
      matrix:
        # Divide the tests into n buckets
        # and run those buckets in parallel.
        # To increase the number of shards,
        # add new items to the shard array
        # and change the value of totalShards
        # to be the length of the shard array.
        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        totalShards: [20]
    needs: [build-core]
    runs-on: ubuntu-22.04
    container:
      # Jammy is Ubuntu 22.04 https://playwright.dev/docs/docker#base-images
      image: mcr.microsoft.com/playwright:v1.33.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/test-core-screenshot
        with:
          shard: ${{ matrix.shard }}
          totalShards: ${{ matrix.totalShards }}
          update: true

  update-reference-screenshots:
    runs-on: ubuntu-22.04
    needs: [test-core-screenshot]
    steps:
      - uses: actions/checkout@v3
        # Normally, we could just push with the
        # default GITHUB_TOKEN, but that will
        # not cause the build workflow
        # to re-run. We use Ionitron's
        # Personal Access Token instead
        # to allow for this build workflow
        # to run when the screenshots are pushed.
        with:
          token: ${{ secrets.IONITRON_TOKEN }}
      - uses: ./.github/workflows/actions/update-reference-screenshots
