name: 'Update Reference Screenshots'

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Which component should be updated? (leave blank to update all)'
        required: false
        default: ''

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build-core

  test-core-screenshot:
    strategy:
      # This ensures that all screenshot shard
      # failures are reported so the dev can
      # review everything at once.
      fail-fast: false
      matrix:
        # Divide the tests into n buckets
        # and run those buckets in parallel.
        # To increase the number of shards,
        # add new items to the shard array
        # and change the value of totalShards
        # to be the length of the shard array.
        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        totalShards: [20]
    needs: [build-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/test-core-screenshot
        with:
          shard: ${{ matrix.shard }}
          totalShards: ${{ matrix.totalShards }}
          update: true
          component: ${{ inputs.component }}

  update-reference-screenshots:
    runs-on: ubuntu-latest
    needs: [test-core-screenshot]
    steps:
      - uses: actions/checkout@v3
        # Normally, we could just push with the
        # default GITHUB_TOKEN, but that will
        # not cause the build workflow
        # to re-run. We use Ionitron's
        # Personal Access Token instead
        # to allow for this build workflow
        # to run when the screenshots are pushed.
        with:
          token: ${{ secrets.IONITRON_TOKEN }}
      - uses: ./.github/workflows/actions/update-reference-screenshots
